// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCErZNyZIc_JYhwfNyJhfcMEU5C_BeH5kE',
    appId: '1:164220448803:web:937557a61c60afabc24196',
    messagingSenderId: '164220448803',
    projectId: 'nouman-learningflutter',
    authDomain: 'nouman-learningflutter.firebaseapp.com',
    storageBucket: 'nouman-learningflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMUzJZAFptFvE2DJnVlEhQ8Gp1aCUxI5M',
    appId: '1:164220448803:android:d52ac4a0fe976324c24196',
    messagingSenderId: '164220448803',
    projectId: 'nouman-learningflutter',
    storageBucket: 'nouman-learningflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNGJbGIkBVTNZoIQUklxC1QV0Xzqw424',
    appId: '1:164220448803:ios:849aca755930aa19c24196',
    messagingSenderId: '164220448803',
    projectId: 'nouman-learningflutter',
    storageBucket: 'nouman-learningflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNGJbGIkBVTNZoIQUklxC1QV0Xzqw424',
    appId: '1:164220448803:ios:849aca755930aa19c24196',
    messagingSenderId: '164220448803',
    projectId: 'nouman-learningflutter',
    storageBucket: 'nouman-learningflutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCErZNyZIc_JYhwfNyJhfcMEU5C_BeH5kE',
    appId: '1:164220448803:web:7924ec8811d26042c24196',
    messagingSenderId: '164220448803',
    projectId: 'nouman-learningflutter',
    authDomain: 'nouman-learningflutter.firebaseapp.com',
    storageBucket: 'nouman-learningflutter.firebasestorage.app',
  );
}
